name: enc-cat-vars
channels:
- anaconda
- conda-forge
dependencies:
- python=3.6.4
- numpy=1.14.1
- scipy=1.0.0
- pandas=0.22.0
- matplotlib=2.1.2
- seaborn=0.8.1
- scikit-learn=0.19.1
- ipython=6.2.1
- notebook=5.4.0
- xlrd=1.1.0
